<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sil</name>
   <tag></tag>
   <elementGuidId>5234ed7a-de16-429c-9291-cebeab59938a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.fa.fa-trash-o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.fa.fa-trash-o</value>
   </webElementProperties>
</WebElementEntity>
