<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SilOnay</name>
   <tag></tag>
   <elementGuidId>33fa49ed-0b63-4c0b-a8ea-db6984900a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.inverted-modal-button.sc-delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.inverted-modal-button.sc-delete</value>
   </webElementProperties>
</WebElementEntity>
