<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FiltreAcildimi</name>
   <tag></tag>
   <elementGuidId>533a8790-67ea-490b-aa59-271503e29eea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dont-close-filterbar.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dont-close-filterbar.active</value>
   </webElementProperties>
</WebElementEntity>
