<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filtre</name>
   <tag></tag>
   <elementGuidId>3011a83f-d078-4243-bd70-319462f6480a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.filter.right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.filter.right</value>
   </webElementProperties>
</WebElementEntity>
