<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menü</name>
   <tag></tag>
   <elementGuidId>83fad880-17b9-4c4e-bfdd-db50187d6897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dropdown</value>
   </webElementProperties>
</WebElementEntity>
