<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mağazalar</name>
   <tag></tag>
   <elementGuidId>cd663fb6-94f8-499b-afb1-b71465f1ba8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.sellerStore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.sellerStore</value>
   </webElementProperties>
</WebElementEntity>
